/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */

import type { ModelMeta } from "@zenstackhq/runtime";

const metadata: ModelMeta = {
    models: {
        user: {
            name: 'User', fields: {
                id: {
                    name: "id",
                    type: "String",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, created_at: {
                    name: "created_at",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, created_by: {
                    name: "created_by",
                    type: "String",
                    isOptional: true,
                }, updated_at: {
                    name: "updated_at",
                    type: "DateTime",
                    attributes: [{ "name": "@updatedAt", "args": [] }],
                }, updated_by: {
                    name: "updated_by",
                    type: "String",
                    isOptional: true,
                }, avatar_url: {
                    name: "avatar_url",
                    type: "String",
                    isOptional: true,
                }, bio: {
                    name: "bio",
                    type: "String",
                    isOptional: true,
                }, dob: {
                    name: "dob",
                    type: "DateTime",
                    isOptional: true,
                }, email: {
                    name: "email",
                    type: "String",
                }, first_name: {
                    name: "first_name",
                    type: "String",
                    isOptional: true,
                }, full_name: {
                    name: "full_name",
                    type: "String",
                    isOptional: true,
                }, gender: {
                    name: "gender",
                    type: "String",
                    isOptional: true,
                }, google_id: {
                    name: "google_id",
                    type: "String",
                    isOptional: true,
                }, is_active: {
                    name: "is_active",
                    type: "Boolean",
                    attributes: [{ "name": "@default", "args": [{ "name": "value", "value": true }] }],
                }, is_delete: {
                    name: "is_delete",
                    type: "Boolean",
                    attributes: [{ "name": "@default", "args": [{ "name": "value", "value": false }] }],
                }, last_name: {
                    name: "last_name",
                    type: "String",
                    isOptional: true,
                }, locale: {
                    name: "locale",
                    type: "String",
                    isOptional: true,
                }, location: {
                    name: "location",
                    type: "String",
                    isOptional: true,
                }, otp: {
                    name: "otp",
                    type: "String",
                    isOptional: true,
                }, otp_generated_time: {
                    name: "otp_generated_time",
                    type: "DateTime",
                    isOptional: true,
                }, password: {
                    name: "password",
                    type: "String",
                }, phone: {
                    name: "phone",
                    type: "String",
                    isOptional: true,
                }, refresh_token: {
                    name: "refresh_token",
                    type: "String",
                    isOptional: true,
                }, reset_password_token: {
                    name: "reset_password_token",
                    type: "String",
                    isOptional: true,
                }, reset_password_token_expiry: {
                    name: "reset_password_token_expiry",
                    type: "DateTime",
                    isOptional: true,
                }, username: {
                    name: "username",
                    type: "String",
                }, current_streak: {
                    name: "current_streak",
                    type: "Int",
                    attributes: [{ "name": "@default", "args": [{ "name": "value", "value": 0 }] }],
                }, last_activity_date: {
                    name: "last_activity_date",
                    type: "DateTime",
                    isOptional: true,
                }, longest_streak: {
                    name: "longest_streak",
                    type: "Int",
                    attributes: [{ "name": "@default", "args": [{ "name": "value", "value": 0 }] }],
                }, ranking_points: {
                    name: "ranking_points",
                    type: "Int",
                    attributes: [{ "name": "@default", "args": [{ "name": "value", "value": 0 }] }],
                }, total_quizzes_completed: {
                    name: "total_quizzes_completed",
                    type: "Int",
                    attributes: [{ "name": "@default", "args": [{ "name": "value", "value": 0 }] }],
                }, posts: {
                    name: "posts",
                    type: "Post",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'author',
                }, user_roles: {
                    name: "user_roles",
                    type: "UserRole",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'user',
                },
            }, uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                }, email: {
                    name: "email",
                    fields: ["email"]
                }, google_id: {
                    name: "google_id",
                    fields: ["google_id"]
                }, phone: {
                    name: "phone",
                    fields: ["phone"]
                }, username: {
                    name: "username",
                    fields: ["username"]
                },
            },
        },
        role: {
            name: 'Role', fields: {
                id: {
                    name: "id",
                    type: "Int",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                    isAutoIncrement: true,
                }, authority: {
                    name: "authority",
                    type: "String",
                }, description: {
                    name: "description",
                    type: "String",
                    isOptional: true,
                }, users: {
                    name: "users",
                    type: "UserRole",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'role',
                }, permissions: {
                    name: "permissions",
                    type: "RolePermission",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'role',
                }, created_at: {
                    name: "created_at",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, updated_at: {
                    name: "updated_at",
                    type: "DateTime",
                    attributes: [{ "name": "@updatedAt", "args": [] }],
                },
            }, uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                }, authority: {
                    name: "authority",
                    fields: ["authority"]
                },
            },
        },
        permission: {
            name: 'Permission', fields: {
                id: {
                    name: "id",
                    type: "Int",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                    isAutoIncrement: true,
                }, name: {
                    name: "name",
                    type: "String",
                }, description: {
                    name: "description",
                    type: "String",
                    isOptional: true,
                }, resource: {
                    name: "resource",
                    type: "String",
                }, action: {
                    name: "action",
                    type: "String",
                }, roles: {
                    name: "roles",
                    type: "RolePermission",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'permission',
                }, created_at: {
                    name: "created_at",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, updated_at: {
                    name: "updated_at",
                    type: "DateTime",
                    attributes: [{ "name": "@updatedAt", "args": [] }],
                },
            }, uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                }, resource_action: {
                    name: "resource_action",
                    fields: ["resource", "action"]
                },
            },
        },
        userRole: {
            name: 'UserRole', fields: {
                user_id: {
                    name: "user_id",
                    type: "String",
                    isId: true,
                    isForeignKey: true,
                    relationField: 'user',
                }, role_id: {
                    name: "role_id",
                    type: "Int",
                    isId: true,
                    isForeignKey: true,
                    relationField: 'role',
                }, assignedAt: {
                    name: "assignedAt",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, user: {
                    name: "user",
                    type: "User",
                    isDataModel: true,
                    backLink: 'user_roles',
                    isRelationOwner: true,
                    onDeleteAction: 'Cascade',
                    foreignKeyMapping: { "id": "user_id" },
                }, role: {
                    name: "role",
                    type: "Role",
                    isDataModel: true,
                    backLink: 'users',
                    isRelationOwner: true,
                    onDeleteAction: 'Cascade',
                    foreignKeyMapping: { "id": "role_id" },
                },
            }, uniqueConstraints: {
                user_id_role_id: {
                    name: "user_id_role_id",
                    fields: ["user_id", "role_id"]
                },
            },
        },
        rolePermission: {
            name: 'RolePermission', fields: {
                role_id: {
                    name: "role_id",
                    type: "Int",
                    isId: true,
                    isForeignKey: true,
                    relationField: 'role',
                }, permission_id: {
                    name: "permission_id",
                    type: "Int",
                    isId: true,
                    isForeignKey: true,
                    relationField: 'permission',
                }, assignedAt: {
                    name: "assignedAt",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, role: {
                    name: "role",
                    type: "Role",
                    isDataModel: true,
                    backLink: 'permissions',
                    isRelationOwner: true,
                    onDeleteAction: 'Cascade',
                    foreignKeyMapping: { "id": "role_id" },
                }, permission: {
                    name: "permission",
                    type: "Permission",
                    isDataModel: true,
                    backLink: 'roles',
                    isRelationOwner: true,
                    onDeleteAction: 'Cascade',
                    foreignKeyMapping: { "id": "permission_id" },
                },
            }, uniqueConstraints: {
                role_id_permission_id: {
                    name: "role_id_permission_id",
                    fields: ["role_id", "permission_id"]
                },
            },
        },
        post: {
            name: 'Post', fields: {
                id: {
                    name: "id",
                    type: "String",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    attributes: [{ "name": "@updatedAt", "args": [] }],
                }, title: {
                    name: "title",
                    type: "String",
                }, content: {
                    name: "content",
                    type: "String",
                }, published: {
                    name: "published",
                    type: "Boolean",
                    attributes: [{ "name": "@default", "args": [{ "name": "value", "value": false }] }],
                }, author: {
                    name: "author",
                    type: "User",
                    isDataModel: true,
                    backLink: 'posts',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "authorId" },
                }, authorId: {
                    name: "authorId",
                    type: "String",
                    isForeignKey: true,
                    relationField: 'author',
                },
            }, uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                },
            },
        },

    },
    deleteCascade: {
        user: ['UserRole'],
        role: ['UserRole', 'RolePermission'],
        permission: ['RolePermission'],

    },
    authModel: 'User'

};
export default metadata;
