/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */

import type { Prisma, UserLearningItem } from "./__types";
import type { UseMutationOptions, UseQueryOptions, UseInfiniteQueryOptions, InfiniteData } from '@tanstack/react-query';
import { getHooksContext } from '@zenstackhq/tanstack-query/runtime-v5/react';
import { useModelQuery, useInfiniteModelQuery, useModelMutation } from '@zenstackhq/tanstack-query/runtime-v5/react';
import type { PickEnumerable, CheckSelect, QueryError, ExtraQueryOptions, ExtraMutationOptions } from '@zenstackhq/tanstack-query/runtime-v5';
import type { PolicyCrudKind } from '@zenstackhq/runtime'
import metadata from './__model_meta';
type DefaultError = QueryError;
import { useSuspenseModelQuery, useSuspenseInfiniteModelQuery } from '@zenstackhq/tanstack-query/runtime-v5/react';
import type { UseSuspenseQueryOptions, UseSuspenseInfiniteQueryOptions } from '@tanstack/react-query';

export function useCreateUserLearningItem(options?: Omit<(UseMutationOptions<(UserLearningItem | undefined), DefaultError, Prisma.UserLearningItemCreateArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.UserLearningItemCreateArgs, DefaultError, UserLearningItem, true>('UserLearningItem', 'POST', `${endpoint}/userLearningItem/create`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.UserLearningItemCreateArgs>(
            args: Prisma.SelectSubset<T, Prisma.UserLearningItemCreateArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, UserLearningItem, Prisma.UserLearningItemGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.UserLearningItemCreateArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, UserLearningItem, Prisma.UserLearningItemGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useCreateManyUserLearningItem(options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.UserLearningItemCreateManyArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.UserLearningItemCreateManyArgs, DefaultError, Prisma.BatchPayload, false>('UserLearningItem', 'POST', `${endpoint}/userLearningItem/createMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.UserLearningItemCreateManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.UserLearningItemCreateManyArgs>,
            options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.UserLearningItemCreateManyArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useFindManyUserLearningItem<TArgs extends Prisma.UserLearningItemFindManyArgs, TQueryFnData = Array<Prisma.UserLearningItemGetPayload<TArgs> & { $optimistic?: boolean }>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.UserLearningItemFindManyArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('UserLearningItem', `${endpoint}/userLearningItem/findMany`, args, options, fetch);
}

export function useInfiniteFindManyUserLearningItem<TArgs extends Prisma.UserLearningItemFindManyArgs, TQueryFnData = Array<Prisma.UserLearningItemGetPayload<TArgs>>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.UserLearningItemFindManyArgs>, options?: Omit<UseInfiniteQueryOptions<TQueryFnData, TError, InfiniteData<TData>>, 'queryKey' | 'initialPageParam'>) {
    options = options ?? { getNextPageParam: () => null };
    const { endpoint, fetch } = getHooksContext();
    return useInfiniteModelQuery<TQueryFnData, TData, TError>('UserLearningItem', `${endpoint}/userLearningItem/findMany`, args, options, fetch);
}

export function useSuspenseFindManyUserLearningItem<TArgs extends Prisma.UserLearningItemFindManyArgs, TQueryFnData = Array<Prisma.UserLearningItemGetPayload<TArgs> & { $optimistic?: boolean }>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.UserLearningItemFindManyArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('UserLearningItem', `${endpoint}/userLearningItem/findMany`, args, options, fetch);
}

export function useSuspenseInfiniteFindManyUserLearningItem<TArgs extends Prisma.UserLearningItemFindManyArgs, TQueryFnData = Array<Prisma.UserLearningItemGetPayload<TArgs>>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.UserLearningItemFindManyArgs>, options?: Omit<UseSuspenseInfiniteQueryOptions<TQueryFnData, TError, InfiniteData<TData>>, 'queryKey' | 'initialPageParam'>) {
    options = options ?? { getNextPageParam: () => null };
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseInfiniteModelQuery<TQueryFnData, TData, TError>('UserLearningItem', `${endpoint}/userLearningItem/findMany`, args, options, fetch);
}

export function useFindUniqueUserLearningItem<TArgs extends Prisma.UserLearningItemFindUniqueArgs, TQueryFnData = Prisma.UserLearningItemGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.UserLearningItemFindUniqueArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('UserLearningItem', `${endpoint}/userLearningItem/findUnique`, args, options, fetch);
}

export function useSuspenseFindUniqueUserLearningItem<TArgs extends Prisma.UserLearningItemFindUniqueArgs, TQueryFnData = Prisma.UserLearningItemGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.UserLearningItemFindUniqueArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('UserLearningItem', `${endpoint}/userLearningItem/findUnique`, args, options, fetch);
}

export function useFindFirstUserLearningItem<TArgs extends Prisma.UserLearningItemFindFirstArgs, TQueryFnData = Prisma.UserLearningItemGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.UserLearningItemFindFirstArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('UserLearningItem', `${endpoint}/userLearningItem/findFirst`, args, options, fetch);
}

export function useSuspenseFindFirstUserLearningItem<TArgs extends Prisma.UserLearningItemFindFirstArgs, TQueryFnData = Prisma.UserLearningItemGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.UserLearningItemFindFirstArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('UserLearningItem', `${endpoint}/userLearningItem/findFirst`, args, options, fetch);
}

export function useUpdateUserLearningItem(options?: Omit<(UseMutationOptions<(UserLearningItem | undefined), DefaultError, Prisma.UserLearningItemUpdateArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.UserLearningItemUpdateArgs, DefaultError, UserLearningItem, true>('UserLearningItem', 'PUT', `${endpoint}/userLearningItem/update`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.UserLearningItemUpdateArgs>(
            args: Prisma.SelectSubset<T, Prisma.UserLearningItemUpdateArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, UserLearningItem, Prisma.UserLearningItemGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.UserLearningItemUpdateArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, UserLearningItem, Prisma.UserLearningItemGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useUpdateManyUserLearningItem(options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.UserLearningItemUpdateManyArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.UserLearningItemUpdateManyArgs, DefaultError, Prisma.BatchPayload, false>('UserLearningItem', 'PUT', `${endpoint}/userLearningItem/updateMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.UserLearningItemUpdateManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.UserLearningItemUpdateManyArgs>,
            options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.UserLearningItemUpdateManyArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useUpsertUserLearningItem(options?: Omit<(UseMutationOptions<(UserLearningItem | undefined), DefaultError, Prisma.UserLearningItemUpsertArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.UserLearningItemUpsertArgs, DefaultError, UserLearningItem, true>('UserLearningItem', 'POST', `${endpoint}/userLearningItem/upsert`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.UserLearningItemUpsertArgs>(
            args: Prisma.SelectSubset<T, Prisma.UserLearningItemUpsertArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, UserLearningItem, Prisma.UserLearningItemGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.UserLearningItemUpsertArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, UserLearningItem, Prisma.UserLearningItemGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useDeleteUserLearningItem(options?: Omit<(UseMutationOptions<(UserLearningItem | undefined), DefaultError, Prisma.UserLearningItemDeleteArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.UserLearningItemDeleteArgs, DefaultError, UserLearningItem, true>('UserLearningItem', 'DELETE', `${endpoint}/userLearningItem/delete`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.UserLearningItemDeleteArgs>(
            args: Prisma.SelectSubset<T, Prisma.UserLearningItemDeleteArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, UserLearningItem, Prisma.UserLearningItemGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.UserLearningItemDeleteArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, UserLearningItem, Prisma.UserLearningItemGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useDeleteManyUserLearningItem(options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.UserLearningItemDeleteManyArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.UserLearningItemDeleteManyArgs, DefaultError, Prisma.BatchPayload, false>('UserLearningItem', 'DELETE', `${endpoint}/userLearningItem/deleteMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.UserLearningItemDeleteManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.UserLearningItemDeleteManyArgs>,
            options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.UserLearningItemDeleteManyArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useAggregateUserLearningItem<TArgs extends Prisma.UserLearningItemAggregateArgs, TQueryFnData = Prisma.GetUserLearningItemAggregateType<TArgs>, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.UserLearningItemAggregateArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('UserLearningItem', `${endpoint}/userLearningItem/aggregate`, args, options, fetch);
}

export function useSuspenseAggregateUserLearningItem<TArgs extends Prisma.UserLearningItemAggregateArgs, TQueryFnData = Prisma.GetUserLearningItemAggregateType<TArgs>, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.UserLearningItemAggregateArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('UserLearningItem', `${endpoint}/userLearningItem/aggregate`, args, options, fetch);
}

export function useGroupByUserLearningItem<TArgs extends Prisma.UserLearningItemGroupByArgs, HasSelectOrTake extends Prisma.Or<Prisma.Extends<'skip', Prisma.Keys<TArgs>>, Prisma.Extends<'take', Prisma.Keys<TArgs>>>, OrderByArg extends Prisma.True extends HasSelectOrTake ? { orderBy: Prisma.UserLearningItemGroupByArgs['orderBy'] } : { orderBy?: Prisma.UserLearningItemGroupByArgs['orderBy'] }, OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<TArgs['orderBy']>>>, ByFields extends Prisma.MaybeTupleToUnion<TArgs['by']>, ByValid extends Prisma.Has<ByFields, OrderFields>, HavingFields extends Prisma.GetHavingFields<TArgs['having']>, HavingValid extends Prisma.Has<ByFields, HavingFields>, ByEmpty extends TArgs['by'] extends never[] ? Prisma.True : Prisma.False, InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
        ? never
        : P extends string
        ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
        : [
            Error,
            'Field ',
            P,
            ` in "having" needs to be provided in "by"`,
        ]
    }[HavingFields]
    : 'take' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields], TQueryFnData = {} extends InputErrors ?
    Array<PickEnumerable<Prisma.UserLearningItemGroupByOutputType, TArgs['by']> &
    {
        [P in ((keyof TArgs) & (keyof Prisma.UserLearningItemGroupByOutputType))]: P extends '_count'
        ? TArgs[P] extends boolean
        ? number
        : Prisma.GetScalarType<TArgs[P], Prisma.UserLearningItemGroupByOutputType[P]>
        : Prisma.GetScalarType<TArgs[P], Prisma.UserLearningItemGroupByOutputType[P]>
    }
    > : InputErrors, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.SubsetIntersection<TArgs, Prisma.UserLearningItemGroupByArgs, OrderByArg> & InputErrors>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('UserLearningItem', `${endpoint}/userLearningItem/groupBy`, args, options, fetch);
}

export function useSuspenseGroupByUserLearningItem<TArgs extends Prisma.UserLearningItemGroupByArgs, HasSelectOrTake extends Prisma.Or<Prisma.Extends<'skip', Prisma.Keys<TArgs>>, Prisma.Extends<'take', Prisma.Keys<TArgs>>>, OrderByArg extends Prisma.True extends HasSelectOrTake ? { orderBy: Prisma.UserLearningItemGroupByArgs['orderBy'] } : { orderBy?: Prisma.UserLearningItemGroupByArgs['orderBy'] }, OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<TArgs['orderBy']>>>, ByFields extends Prisma.MaybeTupleToUnion<TArgs['by']>, ByValid extends Prisma.Has<ByFields, OrderFields>, HavingFields extends Prisma.GetHavingFields<TArgs['having']>, HavingValid extends Prisma.Has<ByFields, HavingFields>, ByEmpty extends TArgs['by'] extends never[] ? Prisma.True : Prisma.False, InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
        ? never
        : P extends string
        ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
        : [
            Error,
            'Field ',
            P,
            ` in "having" needs to be provided in "by"`,
        ]
    }[HavingFields]
    : 'take' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields], TQueryFnData = {} extends InputErrors ?
    Array<PickEnumerable<Prisma.UserLearningItemGroupByOutputType, TArgs['by']> &
    {
        [P in ((keyof TArgs) & (keyof Prisma.UserLearningItemGroupByOutputType))]: P extends '_count'
        ? TArgs[P] extends boolean
        ? number
        : Prisma.GetScalarType<TArgs[P], Prisma.UserLearningItemGroupByOutputType[P]>
        : Prisma.GetScalarType<TArgs[P], Prisma.UserLearningItemGroupByOutputType[P]>
    }
    > : InputErrors, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.SubsetIntersection<TArgs, Prisma.UserLearningItemGroupByArgs, OrderByArg> & InputErrors>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('UserLearningItem', `${endpoint}/userLearningItem/groupBy`, args, options, fetch);
}

export function useCountUserLearningItem<TArgs extends Prisma.UserLearningItemCountArgs, TQueryFnData = TArgs extends { select: any; } ? TArgs['select'] extends true ? number : Prisma.GetScalarType<TArgs['select'], Prisma.UserLearningItemCountAggregateOutputType> : number, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.UserLearningItemCountArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('UserLearningItem', `${endpoint}/userLearningItem/count`, args, options, fetch);
}

export function useSuspenseCountUserLearningItem<TArgs extends Prisma.UserLearningItemCountArgs, TQueryFnData = TArgs extends { select: any; } ? TArgs['select'] extends true ? number : Prisma.GetScalarType<TArgs['select'], Prisma.UserLearningItemCountAggregateOutputType> : number, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.UserLearningItemCountArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('UserLearningItem', `${endpoint}/userLearningItem/count`, args, options, fetch);
}
import type { LearningType } from './__types';

export function useCheckUserLearningItem<TError = DefaultError>(args: { operation: PolicyCrudKind; where?: { created_by?: string; updated_by?: string; id?: number; user_id?: string; question_id?: number; repetitions?: number; interval_days?: number; lapses?: number; consecutive_fails?: number; learning_type?: LearningType }; }, options?: (Omit<UseQueryOptions<boolean, TError, boolean>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<boolean, boolean, TError>('UserLearningItem', `${endpoint}/userLearningItem/check`, args, options, fetch);
}
